---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: bookinfo
spec:
  type: service
  lifecycle: experimental
  owner: developers
  system: applications
  providesApis:
    - bookinfo-api
  dependsOn:
    - component:bookinfo-productpage
    - component:bookinfo-details
    - component:bookinfo-ratings
    - component:bookinfo-reviews
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: bookinfo-productpage
  annotations:
    'backstage.io/kubernetes-label-selector': 'app=productpage'
spec:
  type: service
  lifecycle: experimental
  owner: developers
  system: applications
  subcomponentOf: component:bookinfo
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: bookinfo-details
  annotations:
    'backstage.io/kubernetes-label-selector': 'app=details'
spec:
  type: service
  lifecycle: experimental
  owner: developers
  system: applications
  subcomponentOf: component:bookinfo
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: bookinfo-ratings
  annotations:
    'backstage.io/kubernetes-label-selector': 'app=ratings'
spec:
  type: service
  lifecycle: experimental
  owner: developers
  system: applications
  subcomponentOf: component:bookinfo
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: bookinfo-reviews
  annotations:
    'backstage.io/kubernetes-label-selector': 'app=reviews'
spec:
  type: service
  lifecycle: experimental
  owner: developers
  system: applications
  subcomponentOf: component:bookinfo
